---
- name: Configure OpenSearch using Jinja2 template
  ansible.builtin.template:
    src: opensearch.yml.j2
    dest: "{{ opensearch_config_path }}"
    owner: opensearch
    group: opensearch
    mode: "0640"
  notify: Restart OpenSearch

- name: Enable and start OpenSearch service
  ansible.builtin.systemd_service:
    name: opensearch
    enabled: true
    state: started

- name: Apply pending OpenSearch handler
  ansible.builtin.meta: flush_handlers