---
- name: Restart OpenSearch
  ansible.builtin.systemd_service:
    name: opensearch
    state: restarted

- name: Restart OpenSearch Dashboards
  ansible.builtin.systemd_service:
    name: opensearch-dashboards
    state: restarted

- name: Reload sysctl settings
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: true